services:
  mongo:
    image: mongo:8

    container_name: reports-mongo

    restart: always

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: reportsdb

    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:16

    container_name: reports-postgres

    restart: always

    environment:
      POSTGRES_DB: reportsdb
      POSTGRES_USER: reportsuser
      POSTGRES_PASSWORD: reportspass

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .

    container_name: reports-backend

    restart: always

    depends_on:
      - postgres
      - mongo

    ports:
      - "8080:8080"

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/reportsdb
      DB_USERNAME: reportsuser
      DB_PASSWORD: reportspass

      MONGO_URI: mongodb://mongo:27017/reportsdb

      JWT_SECRET: jwt.secret=mi_clave_super_secreta_de_256_bits_minimo_para_jwt_2026

      CLOUDINARY_CLOUD_NAME: dmz2knvds
      CLOUDINARY_API_KEY: 744686633472466
      CLOUDINARY_API_SECRET: wK190p44-qOla-U-QpN2o1XzI7Q

      GEMINI_API_KEY:

volumes:
  postgres_data:
  mongo_data: